services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
    networks:
      - summai-network
    container_name: summai-server

  webapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.webapp
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=ws://server:8000
    depends_on:
      - server
    networks:
      - summai-network
    container_name: summai-webapp

networks:
  summai-network:
    driver: bridge
